### ISSUE TITLE
Crash on a specific Dockerfile

### ISSUE THREAD

**Issue by grumbach** [buddy-works/dockerfile-linter#11]
Hi! While using dockerfile-linter I encountered the following error, might as well report it!
```
./dockerlinter/lib/groups.js:22
                            name: names[index].trim(),
                                       ^

TypeError: Cannot read property '0' of null
    at ./dockerlinter/lib/groups.js:22:40
    at Array.forEach (<anonymous>)
    at ./dockerlinter/lib/groups.js:20:28
    at Array.forEach (<anonymous>)
    at getEnv (./dockerlinter/lib/groups.js:13:25)
    at ./dockerlinter/lib/groups.js:91:20
    at Array.forEach (<anonymous>)
    at getArgAndEnv (./dockerlinter/lib/groups.js:88:20)
    at replaceArgAndEnv (./dockerlinter/lib/groups.js:178:25)
    at lint (./dockerlinter/app.js:16:14)
```

Steps to reproduce:
Install dockerlinter (--version 1.1.5) with npm
Check this dockerfile

```dockerfile
ENV REDIS_URL redis://redis:6379?socket_timeout=0.5
```

**Comment by BartoszWrobel591** [comment]
Thank you for report, fixed in version 1.2.1
