### ISSUE TITLE
Exception on variable in 'EXPOSE' directive

### ISSUE THREAD

**Issue by srcshelton** [buddy-works/dockerfile-linter#7]
Multi-stage Dockerfile contains:
```
ARG service_ports
FROM image1
...
FROM scratch
ARG service_ports
...
EXPOSE "${service_ports}"
```
... which results in:
```
/dockerfilelinter/lib/lints.js:830
                    return e.match(/\d+/)[0]
                                         ^

TypeError: Cannot read property '0' of null
    at array.map (/dockerfilelinter/lib/lints.js:830:42)
    at Array.map (<anonymous>)
    at Object.validUnixPorts [as EE0001] (/dockerfilelinter/lib/lints.js:827:27)
    at Object.keys.filter.forEach (/dockerfilelinter/app.js:30:21)
    at Array.forEach (<anonymous>)
    at lint (/dockerfilelinter/app.js:29:10)
    at Object.<anonymous> (/dockerfilelinter/bin/dockerfilelinter:34:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```
Version: 1.1.0

**Comment by BartoszWrobel591** [comment]
Thank you for reporting it should be fixed now.
